# Site settings
title: Programming Project
subtitle: on GitHub Pages
email: hoezhanhui@gmail.com
description: A blog about dev projects & //TODO's
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanzhoe.github.io/programmingproject/" # the base hostname & protocol for your site //TODO //fix subscribe css text input color
enforce_ssl: "evanzhoe.github.io/programmingproject/"
paginate_path: "blog/page:num"
author: Zhan Hui
street_address:
city: Madison
state: WI
zip_code: 53706
country: United States of America
phone:


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/evanzhoe
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/zhanhuihoe
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-seo-tag
